[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter ./client build",
  "pnpm --filter ./server build"
]

[start]
cmd = "pnpm --filter ./server start"